package telephone_app.Panels;
import java.sql.*;
import kush.models.Mylib;
import java.awt.event.*;
import java.awt.*;
import javax.swing.*;
import java.util.Date;
/**
 *
 * @author acer
 */
public class AdminReg extends javax.swing.JPanel {

    /**
     * Creates new form AdminReg
     */
    public AdminReg() {
        initComponents();
        setSize(750,750);
        setVisible(true);
        jButton1.addActionListener(new C());
    }
    class C implements ActionListener
    {
       	public void actionPerformed(ActionEvent ae)
		{
                     String t1, t2, t3, t4, t5, t7, t8, t9, t10;

            int t6;
            t1 = jTextField1.getText();
            t2 = jTextField2.getText();
            t3 = jTextField3.getText();
            t4 = jTextField4.getText();
            t5 = jTextField5.getText();
            t6 = Integer.parseInt(jTextField6.getText());
            t7 = jTextField7.getText();
            t8 = jTextField8.getText();
            t9 = jTextField9.getText();
            t10 = jTextField10.getText();
            try {
                Mylib obj = new Mylib();
                Connection cn = obj.createconnection();
                String s1 = "insert into admindata values(?,?,?,?,?,?,?,?,?,?)";
                String s2 = "insert into logindata values(?,?,?,?)";
                PreparedStatement p1 = cn.prepareStatement(s1);
                PreparedStatement p2 = cn.prepareStatement(s2);
                int id = obj.generateId("logindata", 10001);
                p1.setInt(1, id);
                p1.setString(2, t1);
                p1.setString(3, t2);
                p1.setString(4, t3);
                p1.setString(5, t4);
                p1.setString(6, t5);
                p1.setInt(7, t6);
                p1.setString(8, t7);
                p1.setString(9, t8);
                p1.setString(10, t9);

                p2.setInt(1, id);
                p2.setString(2, t1);
                p2.setString(3, t9);
                String role = "admin";
                p2.setString(4, role);

                p1.executeUpdate();
                p2.executeUpdate();

                javax.swing.JOptionPane.showMessageDialog(null, "Equipment ID is : " + id);

                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
                jTextField5.setText("");
                jTextField6.setText("");
                jTextField7.setText("");
                jTextField8.setText("");
                jTextField9.setText("");
                jTextField10.setText("");

            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(null, "" + e);
            }
                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Algerian", 3, 48)); // NOI18N
        jLabel1.setText("ADMIN Registration");
        add(jLabel1);
        jLabel1.setBounds(228, 34, 606, 92);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel2.setText("Name :");
        add(jLabel2);
        jLabel2.setBounds(40, 170, 136, 53);

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel4.setText("Father Name :");
        add(jLabel4);
        jLabel4.setBounds(660, 180, 186, 35);

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel5.setText("Address :");
        add(jLabel5);
        jLabel5.setBounds(40, 250, 124, 35);

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel6.setText("City : ");
        add(jLabel6);
        jLabel6.setBounds(670, 260, 77, 35);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        add(jTextField1);
        jTextField1.setBounds(280, 170, 347, 53);

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel7.setText("PinCode : ");
        add(jLabel7);
        jLabel7.setBounds(670, 320, 136, 54);

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel8.setText("Contact No. : ");
        add(jLabel8);
        jLabel8.setBounds(40, 400, 186, 53);

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel9.setText("Eid : ");
        add(jLabel9);
        jLabel9.setBounds(40, 480, 136, 53);

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel10.setText("Password : ");
        add(jLabel10);
        jLabel10.setBounds(660, 400, 186, 53);

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel11.setText("Confirm Pass : ");
        add(jLabel11);
        jLabel11.setBounds(660, 480, 198, 53);

        jTextField2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        add(jTextField2);
        jTextField2.setBounds(910, 170, 347, 53);

        jTextField3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        add(jTextField3);
        jTextField3.setBounds(280, 250, 347, 53);

        jTextField4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        add(jTextField4);
        jTextField4.setBounds(910, 250, 347, 53);

        jTextField5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        add(jTextField5);
        jTextField5.setBounds(280, 320, 347, 53);

        jTextField6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        add(jTextField6);
        jTextField6.setBounds(910, 320, 347, 53);

        jTextField7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        add(jTextField7);
        jTextField7.setBounds(280, 400, 347, 53);

        jTextField8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        add(jTextField8);
        jTextField8.setBounds(280, 480, 347, 53);

        jTextField9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        add(jTextField9);
        jTextField9.setBounds(900, 400, 347, 53);

        jTextField10.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        add(jTextField10);
        jTextField10.setBounds(900, 480, 347, 53);

        jLabel13.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel13.setText("State");
        add(jLabel13);
        jLabel13.setBounds(40, 330, 130, 50);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton1.setText("Register");
        add(jButton1);
        jButton1.setBounds(400, 600, 230, 50);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
