/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telephone_app.Panels;

/**
 *
 * @author acer
 */
public class RegUpdate extends javax.swing.JPanel {

    /**
     * Creates new form RegUpdate
     */
    public RegUpdate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Algerian", 3, 48)); // NOI18N
        jLabel1.setText("Registration Form");
        add(jLabel1);
        jLabel1.setBounds(259, 47, 550, 60);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel2.setText("First Name : ");
        add(jLabel2);
        jLabel2.setBounds(60, 190, 190, 53);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        add(jTextField1);
        jTextField1.setBounds(340, 200, 350, 53);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel3.setText("Last Name :");
        add(jLabel3);
        jLabel3.setBounds(730, 190, 190, 53);

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel4.setText("Father Name :");
        add(jLabel4);
        jLabel4.setBounds(60, 280, 190, 53);

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel5.setText("Address :");
        add(jLabel5);
        jLabel5.setBounds(730, 280, 190, 53);

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel6.setText("City : ");
        add(jLabel6);
        jLabel6.setBounds(730, 370, 190, 53);

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel7.setText("State :");
        add(jLabel7);
        jLabel7.setBounds(60, 560, 190, 53);

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel8.setText(" PinCode : ");
        add(jLabel8);
        jLabel8.setBounds(730, 560, 190, 53);

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel9.setText("Contact No. : ");
        add(jLabel9);
        jLabel9.setBounds(60, 640, 190, 53);

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel10.setText("Email ID :");
        add(jLabel10);
        jLabel10.setBounds(730, 640, 190, 53);

        jTextField2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        add(jTextField2);
        jTextField2.setBounds(940, 200, 350, 53);

        jTextField3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        add(jTextField3);
        jTextField3.setBounds(340, 280, 350, 53);

        jTextField4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        add(jTextField4);
        jTextField4.setBounds(940, 290, 350, 53);

        jTextField5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        add(jTextField5);
        jTextField5.setBounds(940, 370, 350, 53);

        jTextField6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        add(jTextField6);
        jTextField6.setBounds(340, 560, 350, 53);

        jTextField7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        add(jTextField7);
        jTextField7.setBounds(940, 560, 350, 53);

        jTextField8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        add(jTextField8);
        jTextField8.setBounds(340, 650, 350, 53);

        jTextField9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        add(jTextField9);
        jTextField9.setBounds(940, 650, 350, 53);

        jRadioButton2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jRadioButton2.setText("Female");
        add(jRadioButton2);
        jRadioButton2.setBounds(510, 380, 190, 43);

        jRadioButton1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jRadioButton1.setText("Male");
        add(jRadioButton1);
        jRadioButton1.setBounds(340, 380, 120, 43);

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel11.setText("Gender :");
        jLabel11.setToolTipText("");
        add(jLabel11);
        jLabel11.setBounds(60, 380, 190, 53);

        jLabel12.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel12.setText("Marital Status");
        add(jLabel12);
        jLabel12.setBounds(60, 460, 190, 53);

        jRadioButton3.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jRadioButton3.setText("Married");
        add(jRadioButton3);
        jRadioButton3.setBounds(340, 460, 129, 43);

        jRadioButton4.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jRadioButton4.setText("UnMarried");
        add(jRadioButton4);
        jRadioButton4.setBounds(510, 470, 187, 43);

        jLabel13.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel13.setText("Colony");
        add(jLabel13);
        jLabel13.setBounds(730, 460, 190, 53);

        jTextField10.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        add(jTextField10);
        jTextField10.setBounds(940, 470, 350, 53);

        jLabel14.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel14.setText("Admin ID :");
        add(jLabel14);
        jLabel14.setBounds(70, 120, 150, 60);

        jTextField11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(jTextField11);
        jTextField11.setBounds(340, 130, 350, 50);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton5.setText("Show");
        add(jButton5);
        jButton5.setBounds(750, 130, 140, 50);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton1.setText("Update");
        add(jButton1);
        jButton1.setBounds(160, 740, 160, 50);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton6.setText("Delete");
        add(jButton6);
        jButton6.setBounds(450, 740, 160, 50);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton7.setText("Cancel");
        add(jButton7);
        jButton7.setBounds(720, 740, 160, 50);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
