/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telephone_app.Panels;

import java.awt.event.*;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import kush.models.Mylib;

/**
 *
 * @author acer
 */
public class SearchBy2 extends javax.swing.JPanel {
DefaultTableModel dtm1;
    /**
     * Creates new form SearchBy2
     */
    public SearchBy2() {
        initComponents();
        setSize(1000,1000);
        setVisible(true);
        jButton2.addActionListener(new B());
        dtm1=(DefaultTableModel) jTable1.getModel();
    }
    class B implements ActionListener
    {
        public void actionPerformed(ActionEvent ae)
        {
           String t1;
        t1 = jTextField1.getText();
        try {
            Mylib obj=new Mylib();
            Connection cn=obj.createconnection();

             String sql = "Select * from regdata";
            ResultSet rs = obj.fetchData(sql);
            dtm1= new DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                    
                    
            },
            new String [] {
                "ID", "Name", "Father Name", "Address", "Colony", "Phone Number"
            }
        );
            dtm1.removeRow(0);
            jTable1.setRowHeight(40);

            while (rs.next()) {
                String id, name, father, address, colony, phone;
                colony = rs.getString(11).trim();
                if (colony.equalsIgnoreCase(t1)) {
                    id = rs.getString(1).trim();
                    phone = rs.getString(9).trim();
                    address = rs.getString(5).trim();
                    father = rs.getString(4).trim();
                    name = rs.getString(2).trim();
                    dtm1.addRow(new Object[]{id, name, father, address, colony, phone});
                }
            }
            jTable1.setModel(dtm1);
        } catch (Exception y) {
           javax.swing.JOptionPane.showMessageDialog(null, "" + y);
        } 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Colony : ");
        add(jLabel1);
        jLabel1.setBounds(190, 170, 160, 60);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        add(jTextField1);
        jTextField1.setBounds(340, 180, 350, 50);

        jScrollPane1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Father Name", "Address", "Colony", "Phone Number"
            }
        ));
        jTable1.setIntercellSpacing(new java.awt.Dimension(10, 10));
        jTable1.setMaximumSize(new java.awt.Dimension(2147483647, 15000));
        jTable1.setMinimumSize(new java.awt.Dimension(90, 500));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(20, 400, 1100, 370);

        jLabel2.setFont(new java.awt.Font("Algerian", 3, 48)); // NOI18N
        jLabel2.setText("Search By Colony");
        add(jLabel2);
        jLabel2.setBounds(250, 30, 630, 80);

        jButton2.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        jButton2.setText("Search");
        add(jButton2);
        jButton2.setBounds(350, 290, 240, 50);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
