/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telephone_app.Panels;

import java.awt.event.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JButton;
import kush.models.Mylib;

/**
 *
 * @author acer
 */
public class Show extends javax.swing.JPanel {

    /**
     * Creates new form Show
     */
    public Show() {
        initComponents();
        setSize(1000,1000);
        setVisible(true);
        jButton3.addActionListener(new A());
        jButton4.addActionListener(new C());
    }
class A implements ActionListener
{
    public void actionPerformed(ActionEvent ae)
    {
        String t1, ta;
        t1 = jTextField1.getText();
        JButton BT=(JButton)ae.getSource();
       String sql="SELECT * FROM admindata id=?";
        
        if(BT==jButton4)
        {
            sql=sql+" WHERE AdminID="+jTextField1.getText().trim();
            
        }
        try {

            Mylib obj=new Mylib();
            Connection cn=obj.createconnection();
            Statement st = cn.createStatement();

            ResultSet rs = st.executeQuery(sql);

            String data = "AdminID\tName\tFather\tAddress\tCity\tState\tPinCode\tCntno\tEid\t\tpassword\t";
           
            while (rs.next()) {
                String a1, a2, a3, a4, a5, a6, a7, a8, a9, a10;

                a1 = rs.getString(1);
                a2 = rs.getString(2);
                a3 = rs.getString(3);
                a4 = rs.getString(4);
                a5 = rs.getString(5);
                a6 = rs.getString(6);
                a7 = rs.getString(7);
                a8 = rs.getString(8);
                a9 = rs.getString(9);
                a10 = rs.getString(10);

                data = data + "\n";
                data = data + a1.trim() + "\t";
                data = data + a2.trim() + "\t";
                data = data + a3.trim() + "\t";
                data = data + a4.trim() + "\t";
                data = data + a5.trim() + "\t";
                data = data + a6.trim() + "\t";
                data = data + a7.trim() + "\t";
                data = data + a8.trim() + "\t";
                data = data + a9.trim() + "\t";
                data = data + a10.trim() + "\t";

            }
            jTextArea1.setText(data);
        }
            catch(Exception e)
        {
           javax.swing.JOptionPane.showMessageDialog(null,""+e);
        }
    } 
            
}
class C implements ActionListener
{
    public void actionPerformed(ActionEvent ae)
    {
       String t1, ta;
        t1 = jTextField1.getText();
        
        try {

            Mylib obj=new Mylib();
            Connection cn=obj.createconnection();
            Statement st = cn.createStatement();
            String sql="SELECT * FROM admindata";
            ResultSet rs = st.executeQuery(sql);

            String data = "AdminID\tName\tFather\tAddress\tCity\tState\tPinCode\tCntno\tEid\t\tpassword\t";
            
            while (rs.next()) {
                String a1, a2, a3, a4, a5, a6, a7, a8, a9, a10;

                a1 = rs.getString(1);
                a2 = rs.getString(2);
                a3 = rs.getString(3);
                a4 = rs.getString(4);
                a5 = rs.getString(5);
                a6 = rs.getString(6);
                a7 = rs.getString(7);
                a8 = rs.getString(8);
                a9 = rs.getString(9);
                a10 = rs.getString(10);

                data = data + "\n";
                data = data + a1.trim() + "\t";
                data = data + a2.trim() + "\t";
                data = data + a3.trim() + "\t";
                data = data + a4.trim() + "\t";
                data = data + a5.trim() + "\t";
                data = data + a6.trim() + "\t";
                data = data + a7.trim() + "\t";
                data = data + a8.trim() + "\t";
                data = data + a9.trim() + "\t";
                data = data + a10.trim() + "\t";

            }
            jTextArea1.setText(data);
        }
            catch(Exception e)
        {
           javax.swing.JOptionPane.showMessageDialog(null,""+e);
        } 
    } 
            
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Algerian", 3, 48)); // NOI18N
        jLabel1.setText("Show Admin Form");
        add(jLabel1);
        jLabel1.setBounds(273, 67, 503, 64);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Admin ID :");
        add(jLabel2);
        jLabel2.setBounds(135, 206, 195, 44);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        add(jTextField1);
        jTextField1.setBounds(397, 206, 304, 44);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1);
        jScrollPane1.setBounds(39, 414, 1099, 324);

        jButton3.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        jButton3.setText("Show");
        add(jButton3);
        jButton3.setBounds(240, 320, 200, 60);

        jButton4.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        jButton4.setText("Show All");
        add(jButton4);
        jButton4.setBounds(520, 320, 300, 60);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton jButton3;
    javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
