/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telephone_directory;

import java.sql.*;
import javax.swing.JOptionPane;
import kush.models.Mylib;
/**
 *
 * @author acer
 */
public class RegUpdate extends javax.swing.JFrame {

    /**
     * Creates new form RegUpdate
     */
    public RegUpdate() {
        initComponents();
        setSize(1000,1000);
        setVisible(true);
        jTextField11.requestFocus(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Algerian", 3, 48)); // NOI18N
        jLabel1.setText("Registration Form");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(259, 47, 550, 60);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel2.setText("First Name : ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 190, 190, 53);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(340, 200, 350, 53);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel3.setText("Last Name :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(730, 190, 190, 53);

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel4.setText("Father Name :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 280, 190, 53);

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel5.setText("Address :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(730, 280, 190, 53);

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel6.setText("City : ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(730, 370, 190, 53);

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel7.setText("State :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 560, 190, 53);

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel8.setText(" PinCode : ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(730, 560, 190, 53);

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel9.setText("Contact No. : ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(60, 640, 190, 53);

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel10.setText("Email ID :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(730, 640, 190, 53);

        jTextField2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(940, 200, 350, 53);

        jTextField3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(jTextField3);
        jTextField3.setBounds(340, 280, 350, 53);

        jTextField4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(jTextField4);
        jTextField4.setBounds(940, 290, 350, 53);

        jTextField5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(jTextField5);
        jTextField5.setBounds(940, 370, 350, 53);

        jTextField6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(jTextField6);
        jTextField6.setBounds(340, 560, 350, 53);

        jTextField7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(jTextField7);
        jTextField7.setBounds(940, 560, 350, 53);

        jTextField8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(jTextField8);
        jTextField8.setBounds(340, 650, 350, 53);

        jTextField9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(jTextField9);
        jTextField9.setBounds(940, 650, 350, 53);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton1.setText("Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(760, 120, 133, 52);

        jRadioButton2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jRadioButton2.setText("Female");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(510, 380, 190, 43);

        jRadioButton1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jRadioButton1.setText("Male");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(340, 380, 120, 43);

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel11.setText("Gender :");
        jLabel11.setToolTipText("");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(60, 380, 190, 53);

        jLabel12.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel12.setText("Marital Status");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(60, 460, 190, 53);

        jRadioButton3.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jRadioButton3.setText("Married");
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(340, 460, 129, 43);

        jRadioButton4.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jRadioButton4.setText("UnMarried");
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(510, 470, 187, 43);

        jLabel13.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel13.setText("Colony");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(730, 460, 190, 53);

        jTextField10.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(jTextField10);
        jTextField10.setBounds(940, 470, 350, 53);

        jLabel14.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel14.setText("Registration ID :");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(50, 120, 240, 60);

        jTextField11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(jTextField11);
        jTextField11.setBounds(340, 130, 350, 50);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(160, 740, 180, 50);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(430, 740, 190, 50);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(690, 740, 170, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        try {
            Mylib obj = new Mylib();
            Connection cn = obj.createconnection();
            
            String s1 = "select * from regdata where id=?";
            
            PreparedStatement pst = cn.prepareStatement(s1);
            
            int n =Integer.parseInt(jTextField11.getText().trim());
           
            
            pst.setInt(1, n);

            ResultSet rs = pst.executeQuery();
            
           
            if (rs.next()) {
                String gender =rs.getString("gender");
                String marital = "";
                jTextField11.setEnabled(false);
                jButton1.setEnabled(false);
                jButton2.setEnabled(true);
                jButton3.setEnabled(true);
                jButton4.setEnabled(true);

                jTextField1.setText(rs.getString(2));
                jTextField2.setText(rs.getString(3));
                jTextField3.setText(rs.getString(4));
                jTextField4.setText(rs.getString(5));
                jTextField5.setText(rs.getString(6));
                jTextField6.setText(rs.getString(7));
                jTextField7.setText(rs.getString(8));
                jTextField8.setText(rs.getString(9));
                jTextField9.setText(rs.getString(10));
                jTextField10.setText(rs.getString(11));
                
                if(gender.equalsIgnoreCase("male")) jRadioButton1.setSelected(true);
                else jRadioButton2.setSelected(true);
                
                if(marital.equalsIgnoreCase("married")) jRadioButton3.setSelected(true);
                else jRadioButton4.setSelected(true);
            } 
            else {
                javax.swing.JOptionPane.showMessageDialog(null, "Invalid ID");
            }
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(null, "show ex" + ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
      String t1, t2, t3, t4, t5, t6, t8, t9, t10, t11;
        int t7;
        String gender = "";
        String marital = "";
        t1 = jTextField1.getText();
        t2 = jTextField2.getText();
        t3 = jTextField3.getText();
        t4 = jTextField4.getText();
        t5 = jTextField5.getText();
        t6 = jTextField6.getText();
        t7 = Integer.parseInt(jTextField7.getText());
        t8 = jTextField8.getText();
        t9 = jTextField9.getText();
        t10 = jTextField10.getText();
        t11 = jTextField11.getText();

        try {
            if(jRadioButton1.isSelected()) gender="male";
            else gender="female";
            
          if(jRadioButton3.isSelected()) marital="married";
            else marital="unmarried";
          
            Mylib obj = new Mylib();
            Connection cn = obj.createconnection();
            String sql = "update regdata set first_name=?, last_name=?, fname=?,address=?,city=?,state=?,pincode=?,contact=?,eid=?,colony=?,gender=?,martial=? WHERE id=?";

            PreparedStatement pst = cn.prepareStatement(sql);

            int n = Integer.parseInt(t11.trim());

            pst.setString(1, t1);
            pst.setString(2, t2);
            pst.setString(3, t3);
            pst.setString(4, t4);
            pst.setString(5, t5);
            pst.setString(6, t6);
            pst.setInt(7, t7);
            pst.setString(8, t8);
            pst.setString(9, t9);
            pst.setString(10, t10);

            pst.setInt(11, n);

            int a = pst.executeUpdate();

            if (a == 1) {
                javax.swing.JOptionPane.showMessageDialog(null, "Updated");
                resetform();
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "Not Updated");
            }
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(null, "" + ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String t11;
        t11=jTextField11.getText();
        try {
            
            Mylib obj=new Mylib();
            Connection cn=obj.createconnection();
            
            String sql = "delete FROM regdata WHERE id=?";

            PreparedStatement pst = cn.prepareStatement(sql);

            int n = Integer.parseInt(t11.trim());

            pst.setInt(1, n);

            int aa = pst.executeUpdate();

            if (aa == 1) {
                javax.swing.JOptionPane.showMessageDialog(null, "Data of ID " + n + " is Deleted");
                resetform();
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "Already deleted,cannot delete");
            }
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(null, "" + ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         resetform();
    }//GEN-LAST:event_jButton4ActionPerformed
public void resetform() {

        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        jTextField11.setEnabled(true);
        jButton1.setEnabled(true);
        jTextField11.requestFocus(true);
        
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
        jTextField11.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
