/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telephone_directory;

import java.sql.*;
import javax.swing.table.*;
import kush.models.Mylib;

/**
 *
 * @author acer
 */
public class SearchBy2 extends javax.swing.JFrame {
DefaultTableModel dtm1;
    /**
     * Creates new form SearchBy2
     */
    public SearchBy2() {
        initComponents();
        setSize(1000,1000);
        setVisible(true);
        dtm1=(DefaultTableModel) jTable1.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Colony : ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 170, 160, 60);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(340, 180, 350, 50);

        jButton1.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(330, 290, 250, 60);

        jScrollPane1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Father Name", "Address", "Colony", "Phone Number"
            }
        ));
        jTable1.setIntercellSpacing(new java.awt.Dimension(10, 10));
        jTable1.setMaximumSize(new java.awt.Dimension(2147483647, 15000));
        jTable1.setMinimumSize(new java.awt.Dimension(90, 500));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 400, 1100, 370);

        jLabel2.setFont(new java.awt.Font("Algerian", 3, 48)); // NOI18N
        jLabel2.setText("Search By Colony");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(250, 30, 630, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String t1;
        t1 = jTextField1.getText();
        try {
            Mylib obj=new Mylib();
            Connection cn=obj.createconnection();

             String sql = "Select * from regdata";
            ResultSet rs = obj.fetchData(sql);
            dtm1= new DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                    
                    
            },
            new String [] {
                "ID", "Name", "Father Name", "Address", "Colony", "Phone Number"
            }
        );
            dtm1.removeRow(0);
            jTable1.setRowHeight(40);

            while (rs.next()) {
                String id, name, father, address, colony, phone;
                colony = rs.getString(11).trim();
                if (colony.equalsIgnoreCase(t1)) {
                    id = rs.getString(1).trim();
                    phone = rs.getString(9).trim();
                    address = rs.getString(5).trim();
                    father = rs.getString(4).trim();
                    name = rs.getString(2).trim();
                    dtm1.addRow(new Object[]{id, name, father, address, colony, phone});
                }
            }
            jTable1.setModel(dtm1);
        } catch (Exception y) {
           javax.swing.JOptionPane.showMessageDialog(null, "" + y);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchBy2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchBy2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchBy2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchBy2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchBy2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
