/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telephone_directory;
import java.sql.*;
import javax.swing.*;
import kush.models.Mylib;
/**
 *
 * @author acer
 */
public class Show extends javax.swing.JFrame {

    /**
     * Creates new form Show
     */
    public Show() {
        initComponents();
        setSize(1000, 1000);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Algerian", 3, 48)); // NOI18N
        jLabel1.setText("Show Admin Form");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(273, 67, 503, 64);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Admin ID :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(135, 206, 195, 44);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(397, 206, 304, 44);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButton1.setText("Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(163, 328, 167, 58);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButton2.setText("Show All");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(412, 328, 241, 58);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(39, 414, 1099, 324);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String t1, ta;
        t1 = jTextField1.getText();
        JButton BT=(JButton)evt.getSource();
       String sql="SELECT * FROM admindata AdminID=?";
        
        if(BT==jButton2)
        {
            sql=sql+" WHERE AdminID="+jTextField1.getText().trim();
            
        }
        try {

            Mylib obj=new Mylib();
            Connection cn=obj.createconnection();
            Statement st = cn.createStatement();

            ResultSet rs = st.executeQuery(sql);

            String data = "AdminID\tName\tFather\tAddress\tCity\tState\tPinCode\tCntno\tEid\t\tpassword\t";
           
            while (rs.next()) {
                String a1, a2, a3, a4, a5, a6, a7, a8, a9, a10;

                a1 = rs.getString(1);
                a2 = rs.getString(2);
                a3 = rs.getString(3);
                a4 = rs.getString(4);
                a5 = rs.getString(5);
                a6 = rs.getString(6);
                a7 = rs.getString(7);
                a8 = rs.getString(8);
                a9 = rs.getString(9);
                a10 = rs.getString(10);

                data = data + "\n";
                data = data + a1.trim() + "\t";
                data = data + a2.trim() + "\t";
                data = data + a3.trim() + "\t";
                data = data + a4.trim() + "\t";
                data = data + a5.trim() + "\t";
                data = data + a6.trim() + "\t";
                data = data + a7.trim() + "\t";
                data = data + a8.trim() + "\t";
                data = data + a9.trim() + "\t";
                data = data + a10.trim() + "\t";

            }
            jTextArea1.setText(data);
        }
            catch(Exception e)
        {
           javax.swing.JOptionPane.showMessageDialog(null,""+e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String t1, ta;
        t1 = jTextField1.getText();
        
        try {

            Mylib obj=new Mylib();
            Connection cn=obj.createconnection();
            Statement st = cn.createStatement();
            String sql="SELECT * FROM admindata";
            ResultSet rs = st.executeQuery(sql);

            String data = "AdminID\tName\tFather\tAddress\tCity\tState\tPinCode\tCntno\tEid\t\tpassword\t";
            
            while (rs.next()) {
                String a1, a2, a3, a4, a5, a6, a7, a8, a9, a10;

                a1 = rs.getString(1);
                a2 = rs.getString(2);
                a3 = rs.getString(3);
                a4 = rs.getString(4);
                a5 = rs.getString(5);
                a6 = rs.getString(6);
                a7 = rs.getString(7);
                a8 = rs.getString(8);
                a9 = rs.getString(9);
                a10 = rs.getString(10);

                data = data + "\n";
                data = data + a1.trim() + "\t";
                data = data + a2.trim() + "\t";
                data = data + a3.trim() + "\t";
                data = data + a4.trim() + "\t";
                data = data + a5.trim() + "\t";
                data = data + a6.trim() + "\t";
                data = data + a7.trim() + "\t";
                data = data + a8.trim() + "\t";
                data = data + a9.trim() + "\t";
                data = data + a10.trim() + "\t";

            }
            jTextArea1.setText(data);
        }
            catch(Exception e)
        {
           javax.swing.JOptionPane.showMessageDialog(null,""+e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Show.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Show.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Show.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Show.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Show().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
